accounts/urls.py
from django.urls import include, path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name = 'login'),
    path('logout/',auth_views.LogoutView.as_view(),name = 'logout'),
    path('signup/',views.SignUp.as_view(),name = 'signup'),
]

my_app/urls.py
from django.urls import path
from . import views

app_name = 'my_app'

urlpatterns = [
    path('app_page/',views.AppPage,name = 'app_page'),
]

wat/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage,name = 'index'),
    path('thanks/',views.ThanksPage,name = 'thanks'),
    path('',include('my_app.urls')),
    path('',include('accounts.urls')),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>WAT</title>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
  </head>
  <body>
    <nav class="#263238 blue-grey darken-4 ">
      <!-- <div class=" container nav-wrapper ">
        <a href="/" class="brand-logo">Waatt</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="#">Log In</a></li>
          <li><a href="#">Sign Up</a></li>
        </ul>
      </div>
    </nav>
    <nav> -->
        <div class="container nav-wrapper">
            <a href="/" class="brand-logo left"> <span><strong>Waatt</strong></span> </a>
            <ul class="right">
              {% if user.is_authenticated %}
                <li><a href="/">Home</a></li>
                <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
              {% else %}
                <li><a href="/">Home</a></li>
                <li><a href="{% url 'accounts:login' %}">Log In</a></li>
                <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
              {% endif %}
            </ul>
        </div>
    </nav>
    <br>
  {% block content %}

  {% endblock %}
  <script type="text/javascript">
    $(document).ready(function(){
       $('.modal').modal();
       $('.dropdown-trigger').dropdown();
       $('select').formSelect();
       $('input.autocomplete').autocomplete({
        data: {
          "Apple": null,
          "Microsoft": null,
          "Car": null,
          "Carpet": null,
          "Car Wheels": null,
          "Car Steering": null,
          "LCD TV": null,
          "LED TV": null,
          "Cheap Rooms":null,
          "Cheap Rooms near":null,
          "Table":null,
          "Chair":null,
          "Google": 'https://placehold.it/250x250',

        },
        minLength:4,
        limit:5,
      });
    });

  </script>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
<div id="nav-mobile" class="container">
  <h4 style="text-align: center">Compare all products here from various websites </h4>
  <div class="row">
      <div class="col s4">
          <!--First Icon goes here -->
          <div class="center">
              <i class="medium material-icons" style="color: #EE6E73">devices</i>
              <p>Fast Web Scraper Built with Python</p>
              <p class="light center">Get list of all webistes that has the product available (Instead of visting websites individualy get results here with beautiful GUI).</p>
          </div>
      </div>

      <div class="col s4">
          <!--Second Icon goes here -->
          <div class="center">
              <i class="medium material-icons" style="color: orange">find_replace</i>
              <p>Filter your searches</p>
              <p class="light center">Built in functionality to filter based on pricing and city with autocomplete features.</p>
          </div>
      </div>

      <div class="col s4">
          <!-- Third Icon goes here -->
          <div class="center">
              <i class="medium material-icons" style="color: blue">airplay</i>
              <p>Modern front-end using Materialize</p>
              <p class="light center">
                <a href="https://github.com/mohdnadeem94">Developed by Mohamed Nadeem Ameerdeen</a>
              </p>
          </div>
      </div>
  </div>
  <form action="{% url 'my_app:app_page' %}" method="post" style="text-align: center">
      {% csrf_token %}
      <div class="input-field col s12">
        <input  name="search" type="text" id="autocomplete-input" class="autocomplete">
        <label for="autocomplete-input">Search for the items here</label>
      </div>
      <!-- <input type="text" name="search" placeholder="Search for the items here"> -->
      <div class="row">
        <div class="col s4">
          <select value ="rose" name="rose">
            <option value="best">Best Match</option>
            <option value="plotohi">Price High to Low</option>
            <option value="rlotohi">Ratings Low to High</option>
            <option value="rhitolw">Ratings High to Low</option>
          </select>
        </div>
        <div class="col s4">
          <input type="text" name="min_price" placeholder="Enter the minimum value here">
        </div>
        <div class="col s4">
          <input type="text" name="max_price" placeholder="Enter the maximum value here">
        </div>
      </div>
      <button class="btn waves-effect waves-light" type="submit" name="action" >Submit
          <i class="material-icons right">send</i>
      </button>
  </form>
</div>
{% endblock %}

templates/thanks.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <h4 style="text-align: center">Compare all products here from various websites </h4>
  <div class="row">
      <div class="col s4">
          <!--First Icon goes here -->
          <div class="center">
              <i class="medium material-icons" style="color: #EE6E73">devices</i>
              <p>Fast Web Scraper Built with Python</p>
              <p class="light center">Get list of all webistes that has the product available (Instead of visting websites individualy get results here with beautiful GUI).</p>
          </div>
      </div>

      <div class="col s4">
          <!--Second Icon goes here -->
          <div class="center">
              <i class="medium material-icons" style="color: orange">find_replace</i>
              <p>Filter your searches</p>
              <p class="light center">Built in functionality to filter based on pricing and city with autocomplete features.</p>
          </div>
      </div>

      <div class="col s4">
          <!-- Third Icon goes here -->
          <div class="center">
              <i class="medium material-icons" style="color: blue">airplay</i>
              <p>Modern front-end using Materialize</p>
              <p class="light center">
                <a href="https://github.com/mohdnadeem94">Developed by Mohamed Nadeem Ameerdeen</a>
              </p>
          </div>
      </div>
  </div>
  <form action="{% url 'my_app:app_page' %}" method="post" style="text-align: center">
      {% csrf_token %}
      <div class="input-field col s12">
        <input  name="search" type="text" id="autocomplete-input" class="autocomplete">
        <label for="autocomplete-input">Search for the items here</label>
      </div>
      <!-- <input type="text" name="search" placeholder="Search for the items here"> -->
      <div class="row">
        <div class="col s4">
          <select value ="rose" name="rose">
            <option value="" disabled selected >Sort By</option>
            <option value="atlanta">Price High to Low</option>
            <option value="austin">Ratings Low to High</option>
            <option value="boston">Ratings High to Low</option>
          </select>
        </div>
        <div class="col s4">
          <input type="text" name="min_price" placeholder="Enter the minimum value here">
        </div>
        <div class="col s4">
          <input type="text" name="max_price" placeholder="Enter the maximum value here">
        </div>
      </div>
      <button class="btn waves-effect waves-light" type="submit" name="action" >Submit
          <i class="material-icons right">send</i>
      </button>
  </form>
</div>
{% endblock %}